language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - pip install coveralls nose ordereddict
script:
  # check that the script works as a drop in:
  - python setup.py test
  # now lets do all the tests including doctests and tests for odicti:
  - coverage run --source=pydicti setup.py nosetests
after_success:
  - coveralls
